# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-toml
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.2
    hooks:
    - id: ruff
      # auto fix - use with care! check the allowed fixes in pyproject.toml
      args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
-   repo: https://github.com/adamchainz/django-upgrade
    rev: 1.16.0
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.2"]
-   repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
    -   id: djhtml
        args:
        -   --tabwidth=2
-   repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
    -   id: curlylint
-   repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 37.214.5
    hooks:
        - id: renovate-config-validator
-   repo: https://github.com/mpalmer/action-validator
    rev: v0.6.0
    hooks:
        - id: action-validator
