# Generated by Django 5.0.3 on 2024-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creatures", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creature",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="creature",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
