# Generated by Django 5.0.3 on 2024-03-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creatures", "0002_alter_creature_options_alter_creature_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="creature",
            name="challenge_rating",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="creature",
            name="charisma",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="creature",
            name="constitution",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="creature",
            name="dexterity",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="creature",
            name="intelligence",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="creature",
            name="strength",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="creature",
            name="wisdom",
            field=models.IntegerField(default=10),
        ),
    ]
